---
image_tag: "build"
image_name: "opencontrailnightly/developer-sandbox"
workdir: '{{ zuul.projects | selectattr("short_name", "equalto", "intent-service-dev-env") | map(attribute="src_dir") | list | first }}'

